# Generated by Django 3.1.13 on 2021-11-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_room', to='leases.room'),
        ),
    ]
