# Generated by Django 3.1.13 on 2021-11-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image_likes',
            new_name='room_likes',
        ),
    ]
