# Generated by Django 3.1.13 on 2021-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_auto_20211123_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='phonenumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomnumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='type1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='type2',
            field=models.CharField(max_length=255),
        ),
    ]
