# Generated by Django 3.1.13 on 2021-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_auto_20211123_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='leasename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
