# Generated by Django 3.1.13 on 2021-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_lease_leasename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='leasename',
            field=models.CharField(max_length=255),
        ),
    ]
