# Generated by Django 3.1.13 on 2021-12-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_auto_20211129_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='state',
            field=models.CharField(blank=True, choices=[('step1', '신청'), ('step2', '가계약'), ('step3', '예약완료'), ('step4', '취소')], default='step1', max_length=5),
        ),
    ]
