# Generated by Django 3.1.13 on 2021-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_auto_20211213_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='ed_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='st_date',
            field=models.DateTimeField(),
        ),
    ]
